### ISSUE TITLE
App not installed 

### ISSUE THREAD

**Issue by Sudeep10** [Ahsan40/GLTools#1]
I tried to install the apk..but app not installed ...I am using Android 10 havoc  gsi

Does it work on Android 10 ?

**Comment by Ahsan40** [comment]
Ofiicial apk doesn't support Abdroid 10. Since it's actually the same apk as official just with magisk 20+ support thats why this one also doesn't support android 10. That is the reason you are seeing this error. I wil try to add android 10 support in future.

**Comment by Infector53** [comment]
Hello but in GLTools v4.02 r3.0 No akp file
