### ISSUE TITLE
Unable to install ?

### ISSUE THREAD

**Issue by Cosciad** [Ahsan40/GLTools#2]
Hi, I'm trying to install the APK on my ONEPLUS 3 with lineage 14.1

When I try to install it with the default manager, it tells me that the apk is corrupted.
Here is the message :
INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed reading assets/magisk-template.zip in android.util.jar.StrictJarFile@17f5a0d: META-INF/MANIFEST.MF has invalid digest for assets/magisk-template.zip in assets/magisk-template.zip

What can I do ? =)

**Comment by Ahsan40** [comment]
Looks like it's my fault. I forgot to sign new magisk template. Let me see what I can do.

**Comment by Ahsan40** [comment]
Check new release. I fixed the issue. Hopefully you won't face this issue again.
