### ISSUE TITLE
Hi hacker ;-)

### ISSUE THREAD

**Issue by Cosciad** [Ahsan40/GLTools#3]
![Screenshot_20200416-002744](https://user-images.githubusercontent.com/37622907/79395207-72157280-7f79-11ea-9821-c82bc7e52ff5.png)

This screen appears when you install r2.0 :-(

**Comment by Ahsan40** [comment]
Ah! I forgot about signature verification protection in gltools. I tried to fixed it also in R3. Check out that release and let me know if the problem is still there.

**Comment by Gamemulatorer** [comment]
Same issue #8
