### ISSUE TITLE
Android 10 support

### ISSUE THREAD

**Issue by kiryasmir** [Ahsan40/GLTools#6]
Will it support android 10 someday?

**Comment by Ahsan40** [comment]
Probably.... :3
I am kinda busy right now. 
If I want to add androif 10 I need to disable signature verification first which need a lot of time for this app. Because original dev add some method to protect it and now he stopped development...
So I will try when I get free time....

**Comment by kiryasmir** [comment]
It will be very good. Thanks!

**Comment by Ahsan40** [comment]
> It will be very good. Thanks!
> Is not it possible with lucky patcher?

Nope. License verification of this app implanted very cleverly. It won't be easy. I tried all the easy way. Now all the hard way left but each of them need lot of time to test.
