### ISSUE TITLE
GLTools v4.02 r3.0 Latest released this on Apr 27 still has some license issue

### ISSUE THREAD

**Issue by Gamemulatorer** [Ahsan40/GLTools#8]
@Ahsan40 any fixed?
![Screenshot_20200601-103927](https://user-images.githubusercontent.com/37603562/83371248-865fe280-a3f4-11ea-808e-ff4b0edec221.png)
### phone specs
Android 6.0.1
Mali-450 GPU
Opengl ES 2.0
MAGISK 20.4

**Comment by wefalltomorrow** [comment]
Same issue here sadly.

**Comment by Ahsan40** [comment]
Everyone please wait a little longer. I found a possible way that might works with it but my exam is running from last few weaks. Need one weak more to finish all exams. After that I will try that possible method to fix it. 😅

**Comment by Gamemulatorer** [comment]
> Everyone please wait a little longer. I found a possible way that might works with it but my exam is running from last few weaks. Need one weak more to finish all exams. After that I will try that possible method to fix it.

It's ok just take your time 👍

**Comment by wefalltomorrow** [comment]
> Everyone please wait a little longer. I found a possible way that might works with it but my exam is running from last few weaks. Need one weak more to finish all exams. After that I will try that possible method to fix it. 😅

Much appreciated man, good luck with your exams!

**Comment by Gamemulatorer** [comment]
Im back from CM13 to Stock rom ang GLtools now perfectly work :)

Closing..
